import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Generate a per-animal P&L PDF report and trigger download.
 */
export function generateAnimalPnLPdf(opts: {
  animal: any;
  pnl: any;
  weights: any[];
  currency: string;
  farmName?: string;
}) {
  const { animal, pnl, weights, currency, farmName } = opts;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 40;
  let y = margin;

  // Header
  doc.setFontSize(18);
  doc.setTextColor(15, 110, 86);
  doc.text(farmName ?? "Livestock Farm", margin, y);
  y += 22;
  doc.setFontSize(13);
  doc.setTextColor(0);
  doc.text("Animal P&L Report", margin, y);
  y += 18;
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
  y += 24;

  // Animal info block
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text(`Animal: ${animal.animal.animalId}`, margin, y);
  y += 18;
  doc.setFontSize(10);
  doc.setTextColor(80);
  const info = [
    [`Species: ${animal.speciesName ?? "—"}`, `Category: ${animal.categoryName ?? "—"}`],
    [`Group: ${animal.groupName ?? "—"}`, `Sex: ${animal.animal.sex ?? "—"}`],
    [
      `Acquisition: ${animal.animal.acquisitionDate ? new Date(animal.animal.acquisitionDate).toLocaleDateString() : "—"}`,
      `Status: ${animal.statusName ?? (animal.animal.isActive ? "Active" : "Exited")}`,
    ],
    [
      `Acq Weight: ${animal.animal.weightAtAcquisition ?? "—"} kg`,
      `Target Weight: ${animal.targetWeightKg ?? "—"} kg`,
    ],
  ];
  info.forEach(([left, right]) => {
    doc.text(left, margin, y);
    doc.text(right, margin + 260, y);
    y += 14;
  });
  y += 8;

  // P&L cost breakdown
  const fmt = (n: number) => `${currency} ${(n ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  autoTable(doc, {
    startY: y,
    head: [["Cost component", "Amount"]],
    body: [
      ["Purchase Cost", fmt(pnl?.purchaseCost ?? 0)],
      ["Feed Cost (historical)", fmt(pnl?.feedCost ?? 0)],
      ["Direct Expenses", fmt(pnl?.directExpenseTotal ?? 0)],
      ["Allocated Category Expenses", fmt(pnl?.categoryExpenseAllocation ?? 0)],
      [
        { content: "TOTAL COST", styles: { fontStyle: "bold", fillColor: [240, 230, 220] } },
        { content: fmt(pnl?.totalCost ?? 0), styles: { fontStyle: "bold", fillColor: [240, 230, 220] } },
      ],
      ["Sale Revenue", fmt(pnl?.revenue ?? 0)],
      [
        { content: "NET P&L", styles: { fontStyle: "bold", fillColor: pnl?.netPnL >= 0 ? [220, 240, 220] : [250, 220, 220] } },
        { content: fmt(pnl?.netPnL ?? 0), styles: { fontStyle: "bold", fillColor: pnl?.netPnL >= 0 ? [220, 240, 220] : [250, 220, 220] } },
      ],
    ],
    headStyles: { fillColor: [15, 110, 86], textColor: [255, 255, 255] },
    margin: { left: margin, right: margin },
    styles: { fontSize: 10, cellPadding: 6 },
  });

  y = (doc as any).lastAutoTable.finalY + 18;

  // Derived metrics
  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text("Performance metrics", margin, y);
  y += 14;
  autoTable(doc, {
    startY: y,
    body: [
      ["Days on farm", `${pnl?.daysOnFarm ?? 0} days`],
      ["Cost per day", fmt(pnl?.costPerDay ?? 0)],
      pnl?.pricePerKg > 0 ? ["Price / kg at sale", fmt(pnl.pricePerKg)] : null,
      pnl?.projectedCost ? ["Projected cost (+30d)", fmt(pnl.projectedCost)] : null,
    ].filter(Boolean) as any[][],
    margin: { left: margin, right: margin },
    styles: { fontSize: 10, cellPadding: 5 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 180 } },
    theme: "grid",
  });

  y = (doc as any).lastAutoTable.finalY + 18;

  // Weight history
  if (weights && weights.length > 0) {
    doc.setFontSize(11);
    doc.text("Weight history", margin, y);
    y += 14;
    autoTable(doc, {
      startY: y,
      head: [["Date", "Weight (kg)"]],
      body: weights.map((w: any) => [
        new Date(w.weighDate).toLocaleDateString(),
        parseFloat(w.weightKg).toFixed(2),
      ]),
      headStyles: { fillColor: [83, 74, 183], textColor: [255, 255, 255] },
      margin: { left: margin, right: margin },
      styles: { fontSize: 9, cellPadding: 4 },
    });
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    `Generated by LFMS • ${new Date().toLocaleDateString()}`,
    margin,
    pageHeight - 20
  );

  doc.save(`pnl-${animal.animal.animalId}-${new Date().toISOString().split("T")[0]}.pdf`);
}

/**
 * Generate a farm-wide monthly summary PDF.
 */
export function generateFarmSummaryPdf(opts: {
  fromDate: string;
  toDate: string;
  kpis: any;
  pnlData: any[];
  currency: string;
  farmName?: string;
}) {
  const { fromDate, toDate, kpis, pnlData, currency, farmName } = opts;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 40;
  let y = margin;

  doc.setFontSize(18);
  doc.setTextColor(15, 110, 86);
  doc.text(farmName ?? "Livestock Farm", margin, y);
  y += 22;
  doc.setFontSize(13);
  doc.setTextColor(0);
  doc.text(`Farm Summary: ${fromDate} → ${toDate}`, margin, y);
  y += 18;
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
  y += 24;

  const fmt = (n: number) => `${currency} ${(n ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  // KPI table
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text("Key metrics", margin, y);
  y += 12;
  autoTable(doc, {
    startY: y,
    body: [
      ["Total active heads", String(kpis?.totalActiveHeads ?? 0)],
      ["Total revenue", fmt(kpis?.totalRevenue ?? 0)],
      ["Feed expenses", fmt(kpis?.feedExpenses ?? 0)],
      ["Other expenses", fmt(kpis?.otherExpenses ?? 0)],
      [
        { content: "Total expenses", styles: { fontStyle: "bold" } },
        { content: fmt(kpis?.totalExpenses ?? 0), styles: { fontStyle: "bold" } },
      ],
      [
        { content: "Net P&L", styles: { fontStyle: "bold", fillColor: kpis?.grossPnL >= 0 ? [220, 240, 220] : [250, 220, 220] } },
        { content: fmt(kpis?.grossPnL ?? 0), styles: { fontStyle: "bold", fillColor: kpis?.grossPnL >= 0 ? [220, 240, 220] : [250, 220, 220] } },
      ],
      ["Cost / head / day", `${currency} ${(kpis?.costPerHeadPerDay ?? 0).toFixed(2)}`],
    ],
    margin: { left: margin, right: margin },
    styles: { fontSize: 10, cellPadding: 6 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 200 } },
    theme: "grid",
  });
  y = (doc as any).lastAutoTable.finalY + 18;

  // Category breakdown
  if (kpis?.categoryBreakdown && kpis.categoryBreakdown.length > 0) {
    doc.setFontSize(12);
    doc.text("Category breakdown", margin, y);
    y += 12;
    autoTable(doc, {
      startY: y,
      head: [["Category", "Head count"]],
      body: kpis.categoryBreakdown.map((c: any) => [c.categoryName ?? "Unknown", String(c.headCount)]),
      headStyles: { fillColor: [15, 110, 86], textColor: [255, 255, 255] },
      margin: { left: margin, right: margin },
      styles: { fontSize: 10, cellPadding: 5 },
    });
    y = (doc as any).lastAutoTable.finalY + 18;
  }

  // Top 10 best / worst performers
  const closed = (pnlData ?? [])
    .filter((a: any) => !a.isActive && a.revenue > 0)
    .sort((a: any, b: any) => b.netPnL - a.netPnL);

  if (closed.length > 0) {
    const top = closed.slice(0, 5);
    const bottom = closed.slice(-5).reverse();
    doc.setFontSize(12);
    doc.text("Top 5 best performers (by net P&L)", margin, y);
    y += 12;
    autoTable(doc, {
      startY: y,
      head: [["Animal", "Category", "Days", "Total Cost", "Revenue", "Net P&L"]],
      body: top.map((a: any) => [
        a.animalCode,
        a.categoryName,
        String(a.daysOnFarm),
        fmt(a.totalCost),
        fmt(a.revenue),
        fmt(a.netPnL),
      ]),
      headStyles: { fillColor: [59, 109, 17], textColor: [255, 255, 255] },
      margin: { left: margin, right: margin },
      styles: { fontSize: 9, cellPadding: 4 },
    });
    y = (doc as any).lastAutoTable.finalY + 14;

    if (bottom.length > 0 && bottom[0].animalCode !== top[0].animalCode) {
      doc.setFontSize(12);
      doc.text("Bottom 5 performers", margin, y);
      y += 12;
      autoTable(doc, {
        startY: y,
        head: [["Animal", "Category", "Days", "Total Cost", "Revenue", "Net P&L"]],
        body: bottom.map((a: any) => [
          a.animalCode,
          a.categoryName,
          String(a.daysOnFarm),
          fmt(a.totalCost),
          fmt(a.revenue),
          fmt(a.netPnL),
        ]),
        headStyles: { fillColor: [163, 45, 45], textColor: [255, 255, 255] },
        margin: { left: margin, right: margin },
        styles: { fontSize: 9, cellPadding: 4 },
      });
    }
  }

  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    `Generated by LFMS • ${new Date().toLocaleDateString()}`,
    margin,
    pageHeight - 20
  );

  doc.save(`farm-summary-${fromDate}-to-${toDate}.pdf`);
}
