-- Remove expand-phase columns after 0027 and 0026 rollback.
-- This is destructive to post-expand metadata. Use only inside rollback window.

ALTER TABLE `audit_log` DROP INDEX `audit_log_publicId_unique`, DROP INDEX `audit_log_company_time_idx`, DROP INDEX `audit_log_actor_time_idx`, DROP INDEX `audit_log_request_idx`, DROP INDEX `audit_log_entity_v2_idx`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `membershipId`, DROP COLUMN `platformAdministratorId`, DROP COLUMN `supportAccessGrantId`, DROP COLUMN `actorType`, DROP COLUMN `actionCategory`, DROP COLUMN `userAgent`, DROP COLUMN `requestId`, DROP COLUMN `outcome`, DROP COLUMN `metadata`, DROP COLUMN `version`;
ALTER TABLE `notifications` DROP INDEX `notifications_publicId_unique`, DROP INDEX `notifications_company_id_id_unique`, DROP INDEX `notifications_tenant_deduplication_unique`, DROP INDEX `notifications_company_time_idx`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `expiresAt`, DROP COLUMN `deduplicationKey`, DROP COLUMN `version`;
ALTER TABLE `pregnancy_records` DROP INDEX `pregnancy_records_publicId_unique`, DROP INDEX `pregnancy_records_tenant_active_animal_unique`, DROP INDEX `pregnancy_records_tenant_due_idx`, DROP COLUMN `activeAnimalGuard`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `version`;
ALTER TABLE `expenses` DROP INDEX `expenses_publicId_unique`, DROP INDEX `expenses_scope_date_idx`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `scopeType`, DROP COLUMN `version`;
ALTER TABLE `feed_stock_ledger` DROP INDEX `feed_stock_ledger_publicId_unique`, DROP INDEX `feed_stock_ledger_farm_item_date_idx`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `version`;
ALTER TABLE `ration_plans` DROP INDEX `ration_plans_publicId_unique`, DROP INDEX `ration_plans_scope_active_idx`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `version`;
ALTER TABLE `weight_log` DROP INDEX `weight_log_publicId_unique`, DROP INDEX `weight_log_tenant_animal_date_idx`, DROP INDEX `weight_log_tenant_session_animal_unique`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `version`;
ALTER TABLE `lambing_log` DROP INDEX `lambing_log_publicId_unique`, DROP INDEX `lambing_log_company_id_id_unique`, DROP INDEX `lambing_log_farm_active_code_unique`, DROP INDEX `lambing_log_farm_date_idx`, DROP COLUMN `activeLambCode`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `version`;
ALTER TABLE `sales` DROP INDEX `sales_publicId_unique`, DROP INDEX `sales_tenant_animal_unique`, DROP INDEX `sales_farm_date_idx`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `version`;
ALTER TABLE `animal_status_history` DROP INDEX `animal_status_history_publicId_unique`, DROP INDEX `animal_status_history_tenant_animal_time_idx`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `legacyAnimalId`, DROP COLUMN `animalPublicIdSnapshot`, DROP COLUMN `animalCodeSnapshot`, DROP COLUMN `version`;
ALTER TABLE `animals` DROP INDEX `animals_publicId_unique`, DROP INDEX `animals_company_id_id_unique`, DROP INDEX `animals_farm_active_code_unique`, DROP INDEX `animals_farm_status_idx`, DROP INDEX `animals_company_owner_idx`, DROP COLUMN `activeAnimalCode`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `version`;
ALTER TABLE `system_settings` DROP INDEX `system_settings_publicId_unique`, DROP INDEX `system_settings_company_key_unique`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `version`;
ALTER TABLE `expense_sub_categories` DROP INDEX `expense_sub_categories_publicId_unique`, DROP INDEX `expense_sub_categories_company_id_id_unique`, DROP INDEX `expense_sub_categories_parent_active_name_unique`, DROP COLUMN `activeName`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `deletedAt`, DROP COLUMN `deletedBy`, DROP COLUMN `version`;
ALTER TABLE `expense_categories` DROP INDEX `expense_categories_publicId_unique`, DROP INDEX `expense_categories_company_id_id_unique`, DROP INDEX `expense_categories_company_active_name_unique`, DROP COLUMN `activeName`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `version`;
ALTER TABLE `vaccination_records` DROP INDEX `vaccination_records_publicId_unique`, DROP INDEX `vaccination_records_tenant_animal_due_idx`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `version`;
ALTER TABLE `vaccines` DROP INDEX `vaccines_publicId_unique`, DROP INDEX `vaccines_company_id_id_unique`, DROP INDEX `vaccines_company_active_name_unique`, DROP COLUMN `activeName`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `version`;
ALTER TABLE `feed_item_price_history` DROP INDEX `feed_item_price_history_publicId_unique`, DROP INDEX `feed_item_price_history_scope_date_idx`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `version`;
ALTER TABLE `feed_items` DROP INDEX `feed_items_publicId_unique`, DROP INDEX `feed_items_company_id_id_unique`, DROP INDEX `feed_items_company_active_name_unique`, DROP COLUMN `activeName`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `version`;
ALTER TABLE `birth_types` DROP INDEX `birth_types_publicId_unique`, DROP INDEX `birth_types_company_id_id_unique`, DROP INDEX `birth_types_company_active_name_unique`, DROP COLUMN `activeName`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `version`;
ALTER TABLE `owners` DROP INDEX `owners_publicId_unique`, DROP INDEX `owners_company_id_id_unique`, DROP INDEX `owners_company_active_idx`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `version`;
ALTER TABLE `groups` DROP INDEX `groups_publicId_unique`, DROP INDEX `groups_company_id_id_unique`, DROP INDEX `groups_farm_active_code_unique`, DROP INDEX `groups_farm_active_idx`, DROP COLUMN `activeCode`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `farmId`, DROP COLUMN `version`;
ALTER TABLE `animal_statuses` DROP INDEX `animal_statuses_publicId_unique`, DROP INDEX `animal_statuses_company_id_id_unique`, DROP INDEX `animal_statuses_company_active_name_unique`, DROP COLUMN `activeName`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `version`;
ALTER TABLE `animal_categories` DROP INDEX `animal_categories_publicId_unique`, DROP INDEX `animal_categories_company_id_id_unique`, DROP INDEX `animal_categories_company_active_name_unique`, DROP INDEX `animal_categories_company_active_prefix_unique`, DROP COLUMN `activeName`, DROP COLUMN `activePrefix`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `version`;
ALTER TABLE `species` DROP INDEX `species_publicId_unique`, DROP INDEX `species_company_id_id_unique`, DROP INDEX `species_company_active_name_unique`, DROP INDEX `species_company_active_idx`, DROP COLUMN `activeName`, DROP COLUMN `publicId`, DROP COLUMN `companyId`, DROP COLUMN `version`;
ALTER TABLE `user_settings` DROP INDEX `user_settings_publicId_unique`, DROP INDEX `user_settings_user_company_idx`, DROP COLUMN `publicId`, DROP COLUMN `version`;
ALTER TABLE `users` DROP INDEX `users_publicId_unique`, DROP INDEX `users_normalizedEmail_unique`, DROP COLUMN `publicId`, DROP COLUMN `normalizedEmail`, DROP COLUMN `status`, DROP COLUMN `authVersion`, DROP COLUMN `failedLoginAttempts`, DROP COLUMN `lockedUntil`, DROP COLUMN `lastPasswordChange`, DROP COLUMN `version`;
