export const CONTAINER_ENV_KEYS = [
  "ADMIN_OIDC_CLIENT_ID",
  "ADMIN_OIDC_CLIENT_SECRET",
  "ADMIN_OIDC_ISSUER",
  "ADMIN_OIDC_MFA_ACR_VALUES",
  "ADMIN_OIDC_REDIRECT_URI",
  "ALLOWED_TENANT_ORIGINS",
  "BASE_DOMAIN",
  "BUILT_IN_FORGE_API_KEY",
  "BUILT_IN_FORGE_API_URL",
  "CSP_CONNECT_ORIGINS",
  "CSP_IMAGE_ORIGINS",
  "CSP_SCRIPT_ORIGINS",
  "DATABASE_URL",
  "DB_POOL_CONNECTION_LIMIT",
  "DB_POOL_QUEUE_LIMIT",
  "DEPLOY_VERSION",
  "JWT_SECRET",
  "LOG_LEVEL",
  "METRICS_BEARER_TOKEN",
  "NODE_ENV",
  "OAUTH_ALLOWED_HOSTS",
  "OAUTH_SERVER_URL",
  "OAUTH_STATE_SECRET",
  "OBJECT_STORAGE_ACCESS_KEY_ID",
  "OBJECT_STORAGE_BUCKET",
  "OBJECT_STORAGE_ENDPOINT",
  "OBJECT_STORAGE_KMS_KEY_ID",
  "OBJECT_STORAGE_REGION",
  "OBJECT_STORAGE_SECRET_ACCESS_KEY",
  "OWNER_OPEN_ID",
  "PORT",
  "SESSION_PEPPER",
  "SHUTDOWN_TIMEOUT_MS",
  "VITE_APP_ID",
  "VITE_APP_TITLE",
  "VITE_ANALYTICS_ENDPOINT",
  "VITE_ANALYTICS_WEBSITE_ID",
  "VITE_DEFAULT_DESIGN",
  "VITE_ENABLE_LOCAL_DEV_AUTH",
  "VITE_FRONTEND_FORGE_API_URL",
  "VITE_OAUTH_PORTAL_URL",
  "VITE_SUPPORT_EMAIL",
] as const;

export function collectContainerEnvironment(
  source: Record<string, unknown>
): Record<string, string> {
  const result: Record<string, string> = {};
  for (const key of CONTAINER_ENV_KEYS) {
    const value = source[key];
    if (typeof value === "string" && value.length > 0) result[key] = value;
  }
  const metadata = source.CF_VERSION_METADATA;
  if (
    metadata &&
    typeof metadata === "object" &&
    "id" in metadata &&
    typeof metadata.id === "string"
  ) {
    result.DEPLOY_VERSION = metadata.id;
  }
  return result;
}

export function getConfiguredBaseDomain(
  source: Record<string, unknown>,
  fallback = "l-fms.com"
) {
  const value =
    typeof source.BASE_DOMAIN === "string"
      ? source.BASE_DOMAIN.toLowerCase().replace(/\.$/, "")
      : "";
  const labels = value.split(".");
  return labels.length >= 2 &&
    labels.every(label => /^(?!-)[a-z0-9-]{1,63}(?<!-)$/.test(label))
    ? value
    : fallback;
}

export function getConfiguredInstanceCount(
  source: Record<string, unknown>,
  fallback = 3
) {
  const value = Number(source.CONTAINER_INSTANCE_COUNT);
  return Number.isInteger(value) && value >= 1 && value <= 20
    ? value
    : fallback;
}

export function normalizeEdgeHostname(hostname: string) {
  return hostname.toLowerCase().replace(/\.$/, "");
}

export function isPlatformHostname(hostname: string, baseDomain: string) {
  return (
    normalizeEdgeHostname(hostname) ===
    `admin.${normalizeEdgeHostname(baseDomain)}`
  );
}

export function isLfmsHostname(hostname: string, baseDomain = "l-fms.com") {
  const normalized = normalizeEdgeHostname(hostname);
  const normalizedBase = normalizeEdgeHostname(baseDomain);
  if (normalized === normalizedBase) return true;
  const suffix = `.${normalizedBase}`;
  if (!normalized.endsWith(suffix)) return false;
  const label = normalized.slice(0, -suffix.length);
  return /^(?!-)[a-z0-9-]{1,63}(?<!-)$/.test(label);
}

export function isReservedDeploymentHostname(
  hostname: string,
  baseDomain: string
) {
  const normalized = normalizeEdgeHostname(hostname);
  const stagingRoot = `staging.${normalizeEdgeHostname(baseDomain)}`;
  return normalized === stagingRoot || normalized.endsWith(`.${stagingRoot}`);
}

export function normalizeContainerRequest(request: Request, requestId: string) {
  const url = new URL(request.url);
  const headers = new Headers(request.headers);
  const clientIp = headers.get("cf-connecting-ip");

  headers.delete("forwarded");
  headers.set("x-forwarded-host", url.host);
  headers.set("x-forwarded-port", "443");
  headers.set("x-forwarded-proto", "https");
  headers.set("x-lfms-edge-request-id", requestId);
  if (clientIp) headers.set("x-forwarded-for", clientIp);
  else headers.delete("x-forwarded-for");

  return new Request(request, { headers });
}

export function sanitizeContainerResponse(
  response: Response,
  requestId: string
) {
  // LFMS sets X-Request-Id before any application route. An error without it
  // was generated by the container proxy and may contain a raw exception.
  if (response.status < 400 || response.headers.has("x-request-id")) {
    return response;
  }

  const status = response.status === 429 ? 429 : 503;
  return new Response("Service temporarily unavailable", {
    status,
    headers: {
      "Cache-Control": "no-store",
      "Content-Type": "text/plain; charset=utf-8",
      "Retry-After": response.headers.get("retry-after") ?? "30",
      "X-Request-Id": requestId,
    },
  });
}

function pathMatchesPrefix(pathname: string, prefix: string) {
  return pathname === prefix || pathname.startsWith(`${prefix}/`);
}

export function shouldProxyToContainer(request: Request) {
  if (request.method !== "GET" && request.method !== "HEAD") return true;
  const pathname = new URL(request.url).pathname;
  return (
    ["/api", "/health", "/manus-storage"].some(prefix =>
      pathMatchesPrefix(pathname, prefix)
    ) ||
    pathname === "/metrics" ||
    pathname === "/runtime-config.js"
  );
}

export function resolveEdgeAssetPath(pathname: string, isPlatform: boolean) {
  const shellPath = isPlatform ? "/admin.html" : "/tenant.html";
  if (pathname === "/admin.html" || pathname === "/tenant.html") {
    return null;
  }
  if (pathname === "/assets") return null;
  if (pathname.startsWith("/assets/")) {
    return /^\/assets\/[A-Za-z0-9][A-Za-z0-9._/-]*$/.test(pathname) &&
      !pathname.split("/").includes("..")
      ? pathname
      : null;
  }

  const finalSegment = pathname.slice(pathname.lastIndexOf("/") + 1);
  return finalSegment.includes(".") ? pathname : shellPath;
}

function configuredOrigins(value: unknown) {
  return typeof value === "string"
    ? value
        .split(",")
        .map(origin => origin.trim())
        .filter(Boolean)
    : [];
}

export function secureEdgeResponse(
  response: Response,
  source: Record<string, unknown>,
  requestId: string,
  options: { html?: boolean; platform?: boolean } = {}
) {
  const headers = new Headers(response.headers);
  const storageEndpoint =
    typeof source.OBJECT_STORAGE_ENDPOINT === "string"
      ? source.OBJECT_STORAGE_ENDPOINT
      : "";
  headers.delete("Content-Disposition");
  headers.delete("X-Powered-By");
  headers.set("X-Content-Type-Options", "nosniff");
  headers.set("X-Frame-Options", "DENY");
  headers.set("Referrer-Policy", "strict-origin-when-cross-origin");
  headers.set(
    "Permissions-Policy",
    "camera=(), geolocation=(self), microphone=(self), payment=(), usb=()"
  );
  headers.set("Cross-Origin-Opener-Policy", "same-origin");
  headers.set("Cross-Origin-Resource-Policy", "same-origin");
  headers.set(
    "Content-Security-Policy",
    buildContentSecurityPolicyValue({
      isProduction: true,
      analyticsEndpoint:
        typeof source.VITE_ANALYTICS_ENDPOINT === "string"
          ? source.VITE_ANALYTICS_ENDPOINT
          : undefined,
      scriptOrigins: configuredOrigins(source.CSP_SCRIPT_ORIGINS),
      connectOrigins: [
        ...configuredOrigins(source.CSP_CONNECT_ORIGINS),
        storageEndpoint,
      ],
      imageOrigins: [
        ...configuredOrigins(source.CSP_IMAGE_ORIGINS),
        storageEndpoint,
      ],
      mediaOrigins: [storageEndpoint],
    })
  );
  headers.set(
    "Strict-Transport-Security",
    "max-age=31536000; includeSubDomains; preload"
  );
  headers.set("X-Request-Id", requestId);
  if (options.html) {
    headers.set("Cache-Control", "no-store");
    headers.set("Content-Type", "text/html; charset=utf-8");
  } else if (response.status >= 400) {
    headers.set("Cache-Control", "no-store");
  }
  if (options.platform) {
    headers.set("X-Robots-Tag", "noindex, nofollow, noarchive");
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}
import { buildContentSecurityPolicyValue } from "../shared/contentSecurityPolicy";
